# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-05 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180629_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_nuber',
            new_name='phone_number',
        ),
    ]
