# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='작성자를 입력해 주세요.', max_length=20, verbose_name='작성자')),
                ('title', models.CharField(help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.', max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
