# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180628_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdraw')], default='d', max_length=1),
        ),
    ]
